### ISSUE TITLE
form_rooted_blob, form_multy_blob; mblob, mBlob - or whatever - instead of form_Blob, Blob

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#11]
It's confusing memory and breaks the naming convention of the functions. Yes, for a 300-line long code and functions which are next to each other it's not that critical, but in general it's a bad style, and is making search harder when studying the code.

I know it's applied for other variables, but in the other cases it's logically more coherent - single values, aggregated, ... or they reflect significantly different matters like p and P.

https://github.com/boris-kz/CogAlg/blob/9fa47a929ae39acb1d23dd357a7412c3d28f0a45/frame_dblobs.py#L216

**Comment by boris-kz** [comment]
Yeah... I just changed blob to seg (blob segment) and Blob to blob, that's
more suggestive.
