### ISSUE TITLE
Why rng*2 - even number because p, p-_p ?

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#12]
It's not clear from the explanation in the header why * 2.
I assume because a single comparison requires  at least two comparands?

Lines 67-68, referring to rng2 - means rng*2 ?
 ```
 dP_ = deque()  # line y - 1+ rng2
 dbuff_ = deque()  # line y- 2+ rng2: _Ps buffered by previous run of scan_P_

```

https://github.com/boris-kz/CogAlg/blob/de001789fff4600b91b0ccf336844a4d47ebdb00/frame_dblobs.py#L19

**Comment by boris-kz** [comment]
Because comparison is bi-directional: with before- and after- pixels.
Yes, rng2 = rng*2. Sorry, old comments.

**Comment by Twenkid** [comment]
Before and after + current, i.e. 3 pixels?

**Comment by boris-kz** [comment]
No, rng = 2 before + rng = 2 after. So, it's y == 3 when tuples ders2 are
evaluated.

**Comment by boris-kz** [comment]
Sorry, it's y == 4, because y == 0 only initializes ders
