### ISSUE TITLE
ders2_ - what about another mnemonic identifier?

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#13]
It's said "2D"...

> # comparison between rng vertically consecutive pixels, forming ders2: 2D tuple of derivatives per pixel

What about ders2d_ ? Or dersy, dersY, ders2Y, dersV (vertical)

If the first are "1D" - ders1d (or no change), dersl (lateral, but small L is a bad letter in most fonts), ders1D, dersL 

Or dersx, dersy , or dersX, dersY  or whatever more suggestive.

…

Unless there will be a sequence with numbering: ders3, ders4 etc.... Then it may be consistent with numbers as well.

https://github.com/boris-kz/CogAlg/blob/de001789fff4600b91b0ccf336844a4d47ebdb00/frame_dblobs.py#L64

**Comment by boris-kz** [comment]
I want to keep it brief, for the meaning you can just check content or
comments

**Comment by Twenkid** [comment]
OK
