### ISSUE TITLE
In form_P_ isn't the check if params[0]:  always True as it is coded now?

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#21]
in` form_P_`...  - isn't the last check always True? Or I'm missing something?

x < x_stop is checked for the external cycle as well, so the if params[0] won't be checked if that condition is not met.

At the first pass, s is assigned to be: s = P[0], just before the comparison, thus s == P[0] would always be True at least once, therefore params[0]+=1. 

In order to get x incremented x+=1, thus breaking the the x<x_stop condition on the second pass, L+=1 would be visited at least one.

Maybe x should be incremented once before the internal cycle begins and one more following temporal "s" has to be assigned to the following prospective pattern, which is to be created and compared before the internal cycle?, in order to allow different signs in the first pass - thus allowing cases which skip the internal cycle and make params[0] == 0 to be True sometimes?

```
if params[0]:  # if L > 0
            P_.append(P)  # P is packed into P_
```

```

while x < x_stop:
        s = dert_[x][-1] > 0  # s = g > 0
        params = [0, 0, 0, 0, 0, 0, 0]  # L, Y, X, I, Dy, Dx, G
        **P = [s, params, []]
        while x < x_stop and s == P[0]:**
            i, dy, dx, g = dert_[x, :]  # accumulate P params:
         **params[0] += 1  # L**
            params[1] += y  # Y
            params[2] += x  # X
            params[3] += i  # I
            params[4] += dy # dy
            params[5] += dx # dx
            params[6] += g  # G
            P[2].append((y, x, i, dy, dx, g))
            x += 1
            s = dert_[x][-1] > 0  # s = g > 0

        if params[0]:  # if L > 0
            P_.append(P)  # P is packed into P_
    return P_

```
https://github.com/boris-kz/CogAlg/blob/1ce8aa2c3e4bdcc0259ce2a8c6e83b6a1143a83e/frame_2D_alg/frame_blobs.py#L100

**Comment by khanh93vn** [comment]
Yes, and it seems that is also the case for form_P_() in generic_branch.py. Originally I put it there for bypassing relating bugs, should have put assert there instead. Anyway, it's indeed redundant, will fix that soon. Thanks

**Comment by Twenkid** [comment]
ОК!
