### ISSUE TITLE
Shouldn't it be np.empty(shape=(height, width)...), instead of (width, height)?

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#22]
Shouldn't (height, width) in In `def comp_pixel(frame, p__): ` be **(width, height)?**

`   dert__ = np.empty(shape=(width, height, 4), dtype=int)  # initialize dert__`

The order of dimension declaration in numpy arrays?

According to the code in the initialization:

`height, width = image.shape`

And to code tests like this::

```
 w = 4; h = 2
>>> k = np.zeros(shape=(w,h,1), dtype=int)
>>> k
array([[[0],
        [0]],

       [[0],
        [0]],

       [[0],
        [0]],

       [[0],
        [0]]])
>>> k = np.zeros(shape=(h,w,1), dtype=int)
>>> k
array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

```

https://github.com/boris-kz/CogAlg/blob/1ce8aa2c3e4bdcc0259ce2a8c6e83b6a1143a83e/frame_2D_alg/frame_blobs.py#L61

**Comment by khanh93vn** [comment]
Thanks for discovering it. I'll fix it.

**Comment by Twenkid** [comment]
NP! We should watch about it, it's a common potential mistake in OpenCV-Numpy projects.

**Comment by boris-kz** [comment]
Thanks Todor!
