### ISSUE TITLE
Skip-unpacking of selected tuple elements: for y,x, _, _, _, _ in P[2]: ...

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#23]
Do you know that syntax trick? Probably a bit faster, too. If there are elements of a tuple that won't be used, they could be skipped (readability ("remindability") could be preserved with a comment):

```
  for y, x, _, _, _, _ in P[2]: #   y, x, i, dy, dx, g
                    map[y, x] = True

```
instead of the full form:

```
  for y, x, i, dy, dx, g in P[2]:
                    map[y, x] = True
```

It could be done for any of the positions:
`for y, _, _, dy, _, g in P[2]: `... etc.

https://stackoverflow.com/questions/9532576/ignore-part-of-a-python-tuple

https://github.com/boris-kz/CogAlg/blob/1ce8aa2c3e4bdcc0259ce2a8c6e83b6a1143a83e/frame_2D_alg/frame_blobs.py#L229

**Comment by boris-kz** [comment]
Thanks, I will keep that in mind. Right now it's mostly for
"remindability", less clutter than comments.
For speed, I plan to move to Julia when it gets too slow anyway.
