### ISSUE TITLE
distance_g ... instead of hypot_g? 

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#28]
I am watching the updates in Khan's repository, intra_comp and I see you stick to the Python function name hypot, but IMO a more suggestive name for the CogAlg function is "**distance**", since we are not working with triangles and that concept is used in the introduction.

"Distance" (2D) or "Length" (for a vector) is also how that function is usually called in computer graphics libraries and shader languages, e.g. https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/distance.xhtml

Also "hypot" is only 2D, while distance is generalized for vectors, and I assume that's the goal in the long run, either per derivative and per patterns, and in "clustering": measurement of the distances between the patterns, where a part of the distance is their "pose" - allowed parameter variation within the same-pattern-space, without crossing a border to another pattern, given the selected partitioning of the space of patterns and poses.

def hypot_g(P_, dert_buff___, dert___):

**Comment by boris-kz** [comment]
We already have a more meaningful term for distance: gradient. Hypot_g is
to distinguish it from initial gradient = |dx| + |dy|.

**Comment by Twenkid** [comment]
It is different though, gradient suggests a derivative, a
direction/tendency of change. Hypot or distance is not a derivative in that
sense, no direction (unless you treat its difference to average etc. as a
sign and direction for another calculation).

**Comment by boris-kz** [comment]
>
>
> It is different though, gradient suggests a derivative, a
> direction/tendency of change.


That's exactly what we have. Hypot() is simply a way to compute it.
