### ISSUE TITLE
comp_p development

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#31]
@boris-kz  

Re https://github.com/boris-kz/CogAlg/blob/master/frame_2D_alg/comp_P_draft.py

To begin with the entry point:
```
def comp_P_(val_PP_, blob, xD, rdn):  # scan of vertical Py_ -> comp_P -> 2D mPPs and dPPs, recursion?
    # differential Pm: all params are dderived, not pre-selected?
    s, [min_x, max_x, min_y, max_y, DX, abs_xD, Ly], [L, I, G, Dx, Dy, abs_Dx, abs_Dy], root_ = blob

```
comp_P is called from intra_blob, in the comments:
```
 ...
  comp_P_() if estimated val_PP_ > ave_comp_P, for blob in root_blob.sub_blob_: defined by dx_g:
 ```

Thus in intra_blob there will be some comparison of that val_PP_ 

Apparently comp_P_ uses an outdated structure of the blob, also vars which are not used now? (abs_xD, abs_Dx?) or have to be computed? 

I assume the current intra_blob's top comment structure should be used for the blob and the parameters be adjusted accordingly, through the whole function? 

What is val_PP_? Comparison of some val_ga, val_gg, val_gr? It uses a suffix for a list, but is used as scalar.

Py_ is referred in intra_blobs's seg sub tree, but apparently it should be accessed from different indices than: `Py_ = blob[3][-1]  # per segment, also flip eval per seg?`

**Comment by boris-kz** [comment]
>
>
> def comp_P_(val_PP_, blob, xD, rdn):  # scan of vertical Py_ -> comp_P -> 2D mPPs and dPPs, recursion?
>     # differential Pm: all params are dderived, not pre-selected?
>     s, [min_x, max_x, min_y, max_y, DX, abs_xD, Ly], [L, I, G, Dx, Dy, abs_Dx, abs_Dy], root_ = blob
>
>

comp_P is called from intra_blob, in the comments:
>
>  ...
>   comp_P_() if estimated val_PP_ > ave_comp_P, for blob in root_blob.sub_blob_: defined by dx_g:
>
> Thus in intra_blob there will be some comparison of that val_PP_
>

val_PP_ will be included in sorted vals and dx_g() -> comp_P will be added
to 3 evaluated branches


> Apparently comp_P_ uses an outdated structure of the blob, also vars which
> are not used now? (abs_xD, abs_Dx?) or have to be computed?
>
> I assume the current intra_blob's top comment structure should be used for
> the blob and the parameters be adjusted accordingly, through the whole
> function?
>

Yes, but at this point I only define it to compare params of I + top Dert:
G, Dy, Dx, L, as well as X: ave_x


> What is val_PP_? Comparison of some val_ga, val_gg, val_gr?
>

This is still tentative, in intra_blob comment, II will copy it to top
comment:
 val_PP_ =

L + I + |Dx| + |Dy|  # a superset of Pm, no abs_Dx, abs_Dy for
comp_dert eval: high rdn?
* L / Ly / Ly  # elongation -> Pm incr? ~ box elong: (xn - x0) / (yn - y0)?
* Dy / Dx   # lateral variation & vertical match bias
* Ave / Ga  # angle match rate

It uses a suffix for a list, but is used as scalar.
>

It's an estimated value of converting P_ to PP_


> Py_ is referred in intra_blobs's seg sub tree, but apparently it should be
> accessed from different indices than: Py_ = blob[3][-1] # per segment,
> also flip eval per seg?
>
It will be in segments of blobs produced by dx_g(), similar to hypot_g, but
g is redefined as dx

**Comment by Twenkid** [comment]
What is pPs here? (can't find it elsewhere; the closest is PPs)
 
`def form_PP(typ, P, PP):  # increments continued vPPs or dPPs (not pPs): incr_blob + P_ders?`

In comp_P, is the alteration of identifiers "par-var" just for variety? (In the code it doesn't matter)
```

 for par, C in zip(mPP[1], CmPP_):  # blob-wide summation of 16 summed vars from incr_PP
                    C += par
...
 for var, C in zip(dPP[1], CdPP_):
                    C += var
```

**Comment by boris-kz** [comment]
>
>
> What is pPs here? (can't find it elsewhere; the closest is PPs)
>
Parameter pattern, per d | v of individual parameters. This is very
expensive, so we will need to evaluate for even evaluation of forming them.


> def form_PP(typ, P, PP): # increments continued vPPs or dPPs (not pPs):
> incr_blob + P_ders?
>
> In comp_P, is the alteration of identifiers "par-var" just for variety?
> (In the code it doesn't matter)
>

Var is mostly obsolete, par, is more meaningful. I haven't been updating
comp_P_ much, comp_P needs to be done first.

>

**Comment by Twenkid** [comment]
Pm  +mL? (or dL?)

Pd = ddX + dL + dI + dDx + dDy  #->...

Pm = mX  + dL + vI + mDx + mDy  #-> complem vPP, rdn: stronger Pd|Pm rolp?

**Comment by boris-kz** [comment]
Thanks, that was a typo. Updated version:

dL = L - _L;  mL = min(L, _L)     # comp Derts[1] -> abs match,
dderived rep value is magnitude-proportional?
dDx = Dx - _Dx; mDx = min(Dx, _Dx)
dDy = Dy - _Dy; mDy = min(Dy, _Dy)  # Dy is a higher-precision dI: no
need for comp I? anti-correlated to ortho dDx?

Pd = ddX + dL + dDx + dDy  #-> signed dPP, correlation: dX ->
L,oDy,!oDx, ddX -> dL,odDy,!odDx?
Pm = mX  + mL + mDx + mDy  #-> complem vPP, rdn: stronger Pd|Pm rolp?
