### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#35]
https://github.com/boris-kz/CogAlg/blob/d0abf04dce77298badc906fea971ad322f894c20/frame_2D_alg/alternative%20versions/frame_blobs_cpp_Mayukh/form_P_cpp#L31

```
double at(const double *arr, int r, int c) {
    int index = r * 4 + c;
    return arr[index];
}
```

==>

```
double at(const double *arr, unsigned int r, unsigned int c) {
    auto index = r << 2 + c;
    return arr[index];
}

==>

double at(const double *arr, unsigned int r, unsigned int c) {
    return arr[r << 2 + c];
}
```
...
==>  Direct usage without a function call or suggesting **inline**.

Shift for MUL/DIV by powers of two is a well known trick, but I don't know which compilers apply it and when, also SHIFT for signed int could change the sign.

Also, in the code there's type mixing of float-double-int.

Shared ptr is double (overkill), then read to float, then it's assigned as int/long, all would involve type conversion instructions - is it unavoidable?

**Comment by boris-kz** [comment]
Khanh tried to set up packages to run it, it took too much time, we are not
currently pursuing C++.
