### ISSUE TITLE
issues with comp_g, intra_comp

### ISSUE THREAD

**Issue by khanh93vn** [boris-kz/CogAlg#37]
## Summing of masks
https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L202-L206
Please excuse me, but does this `> 1` intended, or do you mean `> 0`? Even if it's intended, it has no effect on the results, because masks are summed when arrays are broadcast together anyway, like this:
![image](https://user-images.githubusercontent.com/45413044/87875942-c90a6800-c9fe-11ea-86b0-64f0a1bc25ce.png)
Here's what I mean:
![image](https://user-images.githubusercontent.com/45413044/87876287-71213080-ca01-11ea-9fc6-b68c42637df3.png)
Could the summing of masks be put at the end? Could gg's mask be assigned to all other 2D arrays in the returned dert array?

## Incorrect trigonometric identity
https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L217-L218
The cosine of the difference of two angles is:
![image](https://user-images.githubusercontent.com/45413044/87876363-e3921080-ca01-11ea-944f-7418b5cd8efb.png)
(Picture taken from: https://en.wikipedia.org/wiki/List_of_trigonometric_identities)
So those two lines should be:
`cos_da0__ = (cos2__ * cos0__) + (sin2__ * sin0__)  # top left to bottom right`
`cos_da1__ = (cos3__ * cos1__) + (sin3__ * sin1__) # top right to bottom left`

## No need to copy arrays
https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L232-L234
Copying will cause unnecessary overhead in this case. These arrays will be copied when called in ma.stack.

**Comment by kwcckw** [comment]
> 
> ## Summing of masks
> 
> https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L202-L206
> 
> Please excuse me, but does this `> 1` intended, or do you mean `> 0`? Even if it's intended, it has no effect on the results, because masks are summed when arrays are broadcast together anyway, like this:
> ![image](https://user-images.githubusercontent.com/45413044/87875942-c90a6800-c9fe-11ea-86b0-64f0a1bc25ce.png)
> Here's what I mean:
> ![image](https://user-images.githubusercontent.com/45413044/87876287-71213080-ca01-11ea-9fc6-b68c42637df3.png)
> Could the summing of masks be put at the end? Could gg's mask be assigned to all other 2D arrays in the returned dert array?
> 

as i remembered, the value of >1 control the amount of unmasked value, if we increase it to 2 or 3, there would be lesser unmasked value. This is because when we sum them, their value might get more than 1

**Comment by khanh93vn** [comment]
Correct me if I'm wrong, that line has no effect, given the operations 'til it reach gg__, dgy__, dgx__, mg__:
https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L208-L230
Even if you remove that line, results will be the same.

**Comment by boris-kz** [comment]
"The cosine of the difference of two angles is:
image
(Picture taken from: https://en.wikipedia.org/wiki/List_of_trigonometric_identities)
So those two lines should be:
cos_da0__ = (cos2__ * cos0__) + (sin2__ * sin0__) # top left to bottom right
cos_da1__ = (cos3__ * cos1__) + (sin3__ * sin1__) # top right to bottom left
"
Thanks Khanh!

**Comment by boris-kz** [comment]
@khanh93vn , what about cos_da from lines 136-145, is this correct:

        8-tuple of differences between center dert angle and rim dert angle:
        '''
        cos_da = np.stack((
                  ((a__center[0] * a__center[1]) + (a__topleft[0] * a__topleft[1])),
                  ((a__center[0] * a__center[1]) + (a__top[0] *  a__top[1])),
                  ((a__center[0] * a__center[1]) + (a__topright[0] * a__topright[1])),
                  ((a__center[0] * a__center[1]) + (a__right[0] * a__right[1])),
                  ((a__center[0] * a__center[1]) + (a__bottomright[0] * a__bottomright[1])),
                  ((a__center[0] * a__center[1]) + (a__bottom[0] * a__bottom[1])),
                  ((a__center[0] * a__center[1]) + (a__bottomleft[0] * a__bottomleft[1])),
                  ((a__center[0] * a__center[1]) + (a__left[0] * a__left[1]))
                ))

**Comment by kwcckw** [comment]
> 
> 
> Correct me if I'm wrong, that line has no effect, given the operations 'til it reach gg__, dgy__, dgx__, mg__:
> 
> https://github.com/boris-kz/CogAlg/blob/e1d4c44ae364f86b24c2056a80c41d10dc2f2aba/frame_2D_alg/intra_comp.py#L208-L230
> 
> Even if you remove that line, results will be the same.

you mean which line?

**Comment by khanh93vn** [comment]
> you mean which line?

nevermind

> @khanh93vn , what about cos_da from lines 136-145, is this correct:
> 
> ```
>     8-tuple of differences between center dert angle and rim dert angle:
>     '''
>     cos_da = np.stack((
>               ((a__center[0] * a__center[1]) + (a__topleft[0] * a__topleft[1])),
>               ((a__center[0] * a__center[1]) + (a__top[0] *  a__top[1])),
>               ((a__center[0] * a__center[1]) + (a__topright[0] * a__topright[1])),
>               ((a__center[0] * a__center[1]) + (a__right[0] * a__right[1])),
>               ((a__center[0] * a__center[1]) + (a__bottomright[0] * a__bottomright[1])),
>               ((a__center[0] * a__center[1]) + (a__bottom[0] * a__bottom[1])),
>               ((a__center[0] * a__center[1]) + (a__bottomleft[0] * a__bottomleft[1])),
>               ((a__center[0] * a__center[1]) + (a__left[0] * a__left[1]))
>             ))
> ```

Apologise, I haven't check comp_r yet, I'll do it after having patched comp_g up.

**Anyway, if there's no objections, I'll close this issue and push a patch for these 3 problems.**
