### ISSUE TITLE
Did you try it with different images?

### ISSUE THREAD

**Issue by Twenkid** [boris-kz/CogAlg#9]
Does it always enter this segment of the code? With the first image I tested it didn't, with another one - it did.

https://github.com/boris-kz/CogAlg/blob/8a3999311a9d0959de858b04e80d518bd889a725/frame_dblobs.py#L155

See partial log:

It starts with _fork_ = [] and then it gets filled with numbers.

http://twenkid.com/cog/fork.txt

**Comment by boris-kz** [comment]
It does with raccoon. The image shouldn't matter, there is no way a
realistic image wouldn't have a single vertically terminated d sign blob.
